<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
[
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "name": "Fair Rate lets you find the fairrest rate",
    "image": "https://kailashganesh.github.io/fair-rate/src/assets/svgs/home-1.svg",
    "description": "APPLY WITH YOUR HOME</P>\n                        <P class=\"card__content fs-md\">Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "review": {
      "@type": "Review",
      "author": {
        "@type": "Person",
        "name": "Valeria Boltneva"
      },
      "reviewBody": "“FairRate is beautiful, elegant and easy to apply. I’ve been able to apply for an amazing rate in just a minutes. Thank you very much for creating this impressive service!”"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Product",
    "description": "Stop Looking</P>\n                    <P class=\"fs-md clr-content-light mb-5\">Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Praesent commodo cursus magna.</P>\n\n                    <P class=\"fs-md clr-content-light mb-4\">\n                        <SVG class=\"va-middle fill-content-light mr-2\" width=\"24\" height=\"24\">\n                            <use href=\"dist/sprite.svg#icon-tick\"></use>\n                        </SVG>\n                        <SPAN class=\"va-middle\">Integer posuere erat a ante venenatis dapibus.</SPAN>\n                    </P>\n                    <P class=\"fs-md clr-content-light mb-7\">\n                        <SVG class=\"va-middle fill-content-light mr-2\" width=\"24\" height=\"24\">\n                            <use href=\"dist/sprite.svg#icon-tick\"></use>\n                        </SVG>\n                        <SPAN class=\"va-middle\">Donec id elit non mi porta gravida at eget metus."
  }
]
</script>